name: Android CI
on: [push, workflow_dispatch]

env:
  QT_VERSION: 5.15.2

jobs:
  build-engine:
    name: "Build maplibre-gl-native for ${{ matrix.config.abi }}"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - abi: x86
          - abi: x86_64
          - abi: armeabi-v7a
          - abi: arm64-v8a

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: source
          submodules: recursive
          fetch-depth: 0

      - name: Download Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: ${{ env.QT_VERSION }}
          target: android

      - name: Set up OpenJDK 11
        uses: actions/setup-java@v2-preview
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Setup ninja
        uses: seanmiddleditch/gha-setup-ninja@v3

      - name: Set up ccache
        uses: hendrikmuhs/ccache-action@v1
        with:
          key: Android-maplibre-gl-native-${{ matrix.config.abi }}

      - name: Build maplibre-gl-native
        env:
          ANDROID_ABI: ${{ matrix.config.abi }}
        run: |
          export ANDROID_NDK_ROOT="${ANDROID_SDK_ROOT}/ndk-bundle"
          mkdir build && cd build
          cmake ../source/dependencies/maplibre-gl-native \
            -DCMAKE_TOOLCHAIN_FILE="${ANDROID_NDK_ROOT}/build/cmake/android.toolchain.cmake" \
            -DANDROID_ABI="${ANDROID_ABI}" \
            -DANDROID_CCACHE=ccache \
            -DANDROID_NATIVE_API_LEVEL=21 \
            -G Ninja \
            -DMBGL_WITH_QT=ON \
            -DMBGL_QT_LIBRARY_ONLY=ON \
            -DMBGL_QT_STATIC=ON \
            -DMBGL_QT_WITH_INTERNAL_SQLITE=OFF \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_CXX_FLAGS_RELEASE=-g0 \
            -DCMAKE_FIND_ROOT_PATH=${Qt5_Dir} \
            -DCMAKE_PREFIX_PATH=${Qt5_Dir} \
            -DCMAKE_INSTALL_PREFIX=../install-gl
          ninja
          ninja install

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: maplibre-gl-native_Android_${{ matrix.config.abi }}
          path: install-gl

  prepare-engine:
    name: "Prepare maplibre-gl-native"
    runs-on: ubuntu-latest
    needs: build-engine

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: maplibre-gl-native_Android_x86
          path: install-x86
      
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: maplibre-gl-native_Android_x86_64
          path: install-x86_64
      
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: maplibre-gl-native_Android_armeabi-v7a
          path: install-armeabi-v7a

      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: maplibre-gl-native_Android_arm64-v8a
          path: install-arm64-v8a

      - name: Prepare artifacts
        run: |
          cp -r install-arm64-v8a install-gl
          cp install-armeabi-v7a/lib/* install-gl/lib/
          cp install-x86/lib/* install-gl/lib/
          cp install-x86_64/lib/* install-gl/lib/

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: maplibre-gl-native_Android
          path: install-gl

  build-plugin:
    name: "Build qt-geoservices-maplibre"
    runs-on: ubuntu-latest
    needs: prepare-engine

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: source
          fetch-depth: 0

      - name: Download Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: ${{ env.QT_VERSION }}
          target: android

      - name: Set up OpenJDK 11
        uses: actions/setup-java@v2-preview
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Setup ninja
        uses: seanmiddleditch/gha-setup-ninja@v3

      - name: Set up ccache
        uses: hendrikmuhs/ccache-action@v1
        with:
          key: Android-qt-geoservices-maplibre

      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: maplibre-gl-native_Android
          path: install-gl

      - name: Build qt-geoservices-maplibre
        run: |
          export PATH="/usr/lib/ccache:/usr/local/opt/ccache/libexec:$PATH"
          mkdir build && cd build
          qmake ../source/ MBGL_PATH=../install-gl
          make -j2
          INSTALL_ROOT=../install make install

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: qt-geoservices-maplibre_Android
          path: install/home/runner/work/qt-geoservices-maplibre/Qt/${{ env.QT_VERSION }}/android
